name: Deploy Flask App
on:
  push:
    branches:
      - master
jobs:
  # Acessa servidor, atualiza repositorio local, baixa dependencias, reinicia serviço, expoe logs e verifica servico
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Deploy
        uses: matheusvanzan/sshpass-action@v2
        with:
          host: vps51980.publiccloud.com.br
          user: root
          pass: Falhas@#$
          run: |
            cd /root/IA-de-prevencao-de-falhas-na-producao-de-barras
            git fetch
            git checkout master
            git pull
            pip install -r requirements.txt
            systemctl restart prevencaoFalhas.service
            sleep 5
            service prevencaoFalhas status
            journalctl -n 30 -u prevencaoFalhas.service
            systemctl is-active --quiet prevencaoFalhas.service